import {
  MdBed,
  MdBathtub,
  MdKitchen,
  MdWeekend,
  MdChairAlt,
  MdRestaurant,
  MdBalcony,
  MdCheckroom,
  MdShower,
  MdMeetingRoom,
  MdArchive,
  MdLayers,
  MdDeck,
  MdOutlineWorkspacePremium,
  MdGavel,
  MdAssignment,
  MdMap,
  MdArticle,
  MdReceiptLong,
  MdSupervisorAccount,
  MdMarkEmailRead,
  MdHandshake,
  MdBalance,
  MdOutlineDocumentScanner,
  MdElectricalServices,
  MdReceipt,
  MdWaterDrop,
  MdElectricBolt,
  MdSolarPower,
  MdPower,
  MdDelete,
  MdPlumbing,
  MdOpacity,
  MdSettingsInputComponent,
  MdAcUnit,
  MdThermostat,
  MdDirectionsCar,
  MdFence,
  MdAddRoad,
  MdLight,
  MdShoppingCart,
  MdLocalPharmacy,
  MdLocalHospital,
  MdSchool,
  MdChurch,
  MdMosque,
  MdChildFriendly,
  MdDirectionsBus,
  MdLocalAtm,
  MdLocalPolice,
  MdCoPresent,
  MdNoiseControlOff,
  MdDoNotDisturb,
  MdPets,
  MdRequestQuote,
  MdNewReleases,
  MdConstruction,
  MdShield,
  MdChair,
  MdCheckBoxOutlineBlank,
  MdCategory,
  MdFilterBAndW,
  MdPeople,
  MdBusiness,
  MdHome,
  MdSmokeFree,
  MdWaves,
  MdHotTub,
  MdSpa,
  MdWineBar,
  MdLocalBar,
  MdSportsTennis,
  MdSportsBasketball,
  MdFitnessCenter,
  MdGolfCourse,
  MdFlightTakeoff,
  MdDirectionsBoat,
  MdSportsScore,
  MdSmokingRooms,
  MdRouter,
  MdDoorbell,
  MdFingerprint,
  MdVideocam,
  MdRingVolume,
  MdSensors,
  MdNotificationsActive,
  MdSecurity,
  MdLock,
  MdGarage,
  MdSensorWindow,
  MdDoorFront,
  MdGrid3X3,
  MdBlinds,
  MdHolidayVillage,
  MdOutdoorGrill,
  MdYard,
  MdGridOn,
  MdLocalFireDepartment,
  MdBeachAccess,
  MdAgriculture,
  MdSanitizer,
  MdWifiTethering,
  MdGasMeter,
  MdElevator,
  MdAccessibleForward,
  MdDeleteSweep,
  MdCleaningServices,
  MdBatteryChargingFull,
  MdFlashOn,
  MdFireExtinguisher,
  MdMic,
  MdMenuBook,
  MdWbSunny,
  MdEnhancedEncryption,
  MdDns,
  MdHandyman,
  MdContentCut,
  MdEvStation,
  MdLightMode,
  MdEco,
  MdForest,
  MdWindow,
  MdRecycling,
  MdThermostatAuto,
} from 'react-icons/md'

export const iconMap = {
  // Property Features & Rooms
  bed: MdBed,
  bathtub: MdBathtub,
  wc: MdBathtub,
  kitchen: MdKitchen,
  inventory_2: MdArchive,
  inventory: MdArchive,
  weekend: MdWeekend,
  chair_alt: MdChairAlt,
  restaurant: MdRestaurant,
  balcony: MdBalcony,
  checkroom: MdCheckroom,
  shower: MdShower,
  meeting_room: MdMeetingRoom,
  archive: MdArchive,
  layers: MdLayers,
  deck: MdDeck,

  // Documents
  workspace_premium: MdOutlineWorkspacePremium,
  gavel: MdGavel,
  assignment: MdAssignment,
  history_edu: MdArticle,
  map: MdMap,
  article: MdArticle,
  receipt_long: MdReceiptLong,
  supervisor_account: MdSupervisorAccount,
  mark_email_read: MdMarkEmailRead,
  handshake: MdHandshake,
  balance: MdBalance,
  contract: MdOutlineDocumentScanner,

  // Utilities
  electric_meter: MdElectricalServices,
  receipt: MdReceipt,
  water_drop: MdWaterDrop,
  electric_bolt: MdElectricBolt,
  solar_power: MdSolarPower,
  power: MdPower,
  water: MdWaterDrop,
  delete: MdDelete,
  plumbing: MdPlumbing,
  opacity: MdOpacity,
  settings_input_component: MdSettingsInputComponent,
  ac_unit: MdAcUnit,
  thermostat: MdThermostat,

  // Community & Lifestyle
  directions_car: MdDirectionsCar,
  fence: MdFence,
  add_road: MdAddRoad,
  light: MdLight,
  shopping_cart: MdShoppingCart,
  local_pharmacy: MdLocalPharmacy,
  local_hospital: MdLocalHospital,
  school: MdSchool,
  church: MdChurch,
  mosque: MdMosque,
  child_friendly: MdChildFriendly,
  directions_bus: MdDirectionsBus,
  local_atm: MdLocalAtm,
  local_police: MdLocalPolice,
  co_present: MdCoPresent,

  // Property Rules
  noise_control_off: MdNoiseControlOff,
  do_not_disturb: MdDoNotDisturb,
  pets: MdPets,
  request_quote: MdRequestQuote,
  new_releases: MdNewReleases,
  construction: MdConstruction,
  shield: MdShield,
  chair: MdChair,
  check_box_outline_blank: MdCheckBoxOutlineBlank,
  category: MdCategory,
  filter_b_and_w: MdFilterBAndW,
  person: MdChair,
  people: MdPeople,
  business: MdBusiness,
  home: MdHome,
  smoke_free: MdSmokeFree,

  // Luxury & Leisure
  pool: MdWaterDrop,
  waves: MdWaves,
  hot_tub: MdHotTub,
  spa: MdSpa,
  wine_bar: MdWineBar,
  local_bar: MdLocalBar,
  sports_tennis: MdSportsTennis,
  sports_basketball: MdSportsBasketball,
  fitness_center: MdFitnessCenter,
  golf_course: MdGolfCourse,
  flight_takeoff: MdFlightTakeoff,
  directions_boat: MdDirectionsBoat,
  roofing: MdDeck,
  sports_score: MdSportsScore,
  smoking_rooms: MdSmokingRooms,

  // Security & Smart Home
  router: MdRouter,
  doorbell: MdDoorbell,
  fingerprint: MdFingerprint,
  bolt: MdElectricBolt,
  videocam: MdVideocam,
  ring_volume: MdRingVolume,
  sensors: MdSensors,
  notifications_active: MdNotificationsActive,
  security: MdSecurity,
  lock: MdLock,
  garage: MdGarage,
  detector_smoke: MdSensorWindow,
  door_front: MdDoorFront,
  grid_3x3: MdGrid3X3,
  blinds: MdBlinds,

  // Outdoor & Landscaping
  holiday_village: MdHolidayVillage,
  outdoor_grill: MdOutdoorGrill,
  yard: MdYard,
  grid_on: MdGridOn,
  local_fire_department: MdLocalFireDepartment,
  beach_access: MdBeachAccess,
  agriculture: MdAgriculture,
  grass: MdEco,

  // Core Infrastructure
  sanitizer: MdSanitizer,
  wifi_tethering: MdWifiTethering,
  gas_meter: MdGasMeter,
  accessible_forward: MdAccessibleForward,
  delete_sweep: MdDeleteSweep,
  cleaning_services: MdCleaningServices,
  battery_charging_full: MdBatteryChargingFull,
  flash_on: MdFlashOn,
  fire_extinguisher: MdFireExtinguisher,
  hvac: MdAcUnit,
  unfold_more: MdElevator,

  // Specialized Rooms
  cottage: MdHome,
  theaters: MdChair,
  desk: MdDeck,
  place_of_worship: MdChurch,
  local_laundry_service: MdCleaningServices,
  foundation: MdHome,
  sports_esports: MdChair,
  mic: MdMic,
  menu_book: MdMenuBook,
  wb_sunny: MdWbSunny,
  enhanced_encryption: MdEnhancedEncryption,
  dns: MdDns,
  handyman: MdHandyman,
  content_cut: MdContentCut,

  // Eco-Friendly
  ev_station: MdEvStation,
  light_mode: MdLightMode,
  eco: MdEco,
  forest: MdForest,
  window: MdWindow,
  recycling: MdRecycling,
  nest_thermostat: MdThermostatAuto,
  water_ec: MdWaterDrop,
  science: MdEco,
}

export type IconKey = keyof typeof iconMap

export const getIcon = (iconName: IconKey) => {
  return iconMap[iconName]
}
