import faq from './faq'
import blog from './blog'
import blockContent from './blockContent'
import listing from './listing'
import listingForm from './listingForm'
import agent from './agent'
import client from './client'
import deal from './deal'
import team from './team'
import contact from './contact'
import portfolio from './portfolio'
import inspection from './inspection'
import testimonal from './testimonal'
import youtube from './youtube'

export const schemaTypes = [faq, blog, blockContent, client, deal, listing, listingForm, agent, team, contact, portfolio, inspection, testimonal, youtube]
