import {defineArrayMember, defineField, defineType} from 'sanity'
import {
  MdBed,
  MdBathtub,
  MdKitchen,
  MdWeekend,
  MdChairAlt,
  MdRestaurant,
  MdBalcony,
  MdCheckroom,
  MdShower,
  MdMeetingRoom,
  MdArchive,
  MdLayers,
  MdDeck,
  MdOutlineWorkspacePremium ,
  MdGavel,
  MdAssignment,
  MdMap,
  MdArticle,
  MdReceiptLong,
  MdSupervisorAccount,
  MdMarkEmailRead,
  MdHandshake,
  MdBalance,
  MdOutlineDocumentScanner ,
  MdElectricalServices,
  MdReceipt,
  MdWaterDrop,
  MdElectricBolt,
  MdSolarPower,
  MdPower,
  MdDelete,
  MdPlumbing,
  MdOpacity,
  MdSettingsInputComponent,
  MdAcUnit,
  MdThermostat,
  MdDirectionsCar,
  MdFence,
  MdAddRoad,
  MdLight,
  MdShoppingCart,
  MdLocalPharmacy,
  MdLocalHospital,
  MdSchool,
  MdChurch,
  MdMosque,
  MdChildFriendly,
  MdDirectionsBus,
  MdLocalAtm,
  MdLocalPolice,
  MdCoPresent,
  MdNoiseControlOff,
  MdDoNotDisturb,
  MdPets,
  MdRequestQuote,
  MdNewReleases,
  MdConstruction,
  MdShield,
  MdChair,
  MdCheckBoxOutlineBlank,
  MdCategory,
  MdFilterBAndW,
  MdPeople,
  MdBusiness,
  MdHome,
  MdSmokeFree,
  MdWaves,
  MdHotTub,
  MdSpa,
  MdWineBar,
  MdLocalBar,
  MdSportsTennis,
  MdSportsBasketball,
  MdFitnessCenter,
  MdGolfCourse,
  MdFlightTakeoff,
  MdDirectionsBoat,
  MdSportsScore,
  MdSmokingRooms,
  MdRouter,
  MdDoorbell,
  MdFingerprint,
  MdVideocam,
  MdRingVolume,
  MdSensors,
  MdNotificationsActive,
  MdSecurity,
  MdLock,
  MdGarage,
  MdSensorWindow,
  MdDoorFront,
  MdGrid3X3,
  MdBlinds,
  MdHolidayVillage,
  MdOutdoorGrill,
  MdYard,
  MdGridOn,
  MdLocalFireDepartment,
  MdBeachAccess,
  MdAgriculture,
  MdSanitizer,
  MdWifiTethering,
  MdGasMeter,
  MdElevator,
  MdAccessibleForward,
  MdDeleteSweep,
  MdCleaningServices,
  MdBatteryChargingFull,
  MdFlashOn,
  MdFireExtinguisher,
  MdMic,
  MdMenuBook,
  MdWbSunny,
  MdEnhancedEncryption,
  MdDns,
  MdHandyman,
  MdContentCut,
  MdEvStation,
  MdLightMode,
  MdEco,
  MdForest,
  MdWindow,
  MdRecycling,
  MdThermostatAuto,
  MdDomainVerification,
  MdSportsEsports,
  MdTheaters,
  MdSportsHockey,
  MdLocalPlay,
  MdSmartDisplay,
  MdConnectedTv,
} from 'react-icons/md'

export default defineType({
  name: 'listing',
  title: 'Listing',
  type: 'document',
  initialValue: () => {
    // Use crypto.randomUUID() if available (modern browsers), otherwise fallback
    const generateId = () => {
      if (typeof crypto !== 'undefined' && crypto.randomUUID) {
        return crypto.randomUUID();
      }
      // Fallback: timestamp + random hex (still very unlikely to collide)
      return Date.now().toString(36) + '-' + Math.random().toString(36).substring(2, 8);
    };
    const uniqueId = generateId();
    // You can format it as you like, e.g., "LS-" + first 8 chars of UUID
    const code = `LS-${uniqueId.slice(0, 8)}`.toUpperCase();
    return { listingCode: code };
  },
  
  fields: [
    defineField({
      name: "listingCode",
      title: "Listing Code",
      type: "string",
      readOnly: true,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: (doc) => `${doc?.title ?? ''}-${doc?.listingCode ?? ''}`,
        maxLength: 120,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      options: {
        list: [
          {title: 'Active', value: 'active'},
          {title: 'Inactive', value: 'inactive'},
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      options: {
        list: [
          {title: 'For Sale', value: 'for-sale'},
          {title: 'For Rent', value: 'for-rent'},
          {title: 'Shortlet', value: 'shortlet'},
        ],
      },
    }),
    defineField({
      name: 'propertyType',
      title: 'Property Type',
      type: 'string',
      options: {
        list: [
          {title: 'Flats & Apartments', value: 'flats-apartments'},
          {title: 'Warehouse', value: 'warehouse'},
          {title: 'Lands', value: 'lands'},
          {title: 'Maisonette', value: 'maisonette'},
          {title: 'Penthouse', value: 'penthouse'},
          {title: 'Mini Flats', value: 'mini-flats'},
          {title: 'Terraced Duplex', value: 'terraced-duplex'},
          {title: 'Detached Duplex', value: 'detached-duplex'},
          {title: 'Semi Detached Duplex', value: 'semi-detached-duplex'},
          {title: 'Commercial', value: 'commercial'},
          {title: 'Bungalow', value: 'bungalow'},
          {title: 'Duplex', value: 'duplex'},
        ],
        layout: 'dropdown',
      },
    }),
    defineField({
      name: 'price',
      title: 'Price',
      type: 'number',
      description: '250000000',
      validation: (Rule) => Rule.integer().positive(),
    }),
    defineField({
      name: 'city',
      title: 'City',
      type: 'string',
    }),
    defineField({
      name: 'state',
      title: 'State',
      type: 'string',
    }),
    defineField({
      name: 'bedrooms',
      title: 'Bedrooms',
      type: 'string',
      description: 'Example: 4 Bedrooms',
    }),
    defineField({
      name: 'baths',
      title: 'Baths',
      type: 'string',
      description: 'Example: 2 Baths',
    }),
    defineField({
      name: 'videoUrl',
      title: 'Video Tour Link',
      type: 'string',
    }),
    defineField({
      name: 'gallery',
      title: 'Gallery',
      type: 'array',
      of: [defineArrayMember({type: 'image', options: {hotspot: true}})],
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'blockContent',
    }),
    defineField({
      name: 'unit',
      title: 'Unit Available',
      type: 'number',
    }),
    defineField({
      name: 'featured',
      title: 'Flag Property as featured',
      type: 'boolean',
    }),

    // Property Features & Rooms
    defineField({
      name: 'propertyFeatures',
      title: 'Property Features & Rooms',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      options: {
        list: [
          {title: 'Guest Toilet', value: 'wc', icon: MdBathtub},
          {title: 'Kitchen', value: 'kitchen', icon: MdKitchen},
          {title: 'Pantry', value: 'inventory_2', icon: MdArchive},
          {title: 'Store Room', value: 'inventory', icon: MdArchive},
          {title: 'Living Room / Lounge', value: 'weekend', icon: MdWeekend},
          {title: 'Family Lounge (Upstairs)', value: 'chair_alt', icon: MdChairAlt},
          {title: 'Dining Area', value: 'restaurant', icon: MdRestaurant},
          {title: 'Balcony / Terrace', value: 'balcony', icon: MdBalcony},
          {title: 'Walk-in Closet', value: 'checkroom', icon: MdCheckroom},
          {title: 'En-suite Bathrooms', value: 'shower', icon: MdShower},
          {title: 'Ante Room / Foyer', value: 'meeting_room', icon: MdMeetingRoom},
          {title: 'Box Room / Extra Storage', value: 'archive', icon: MdArchive},
          {title: 'Mezzanine Level', value: 'layers', icon: MdLayers},
          {title: 'Verandah', value: 'deck', icon: MdDeck},
        ],
      },
    }),

    // Available Documents
    defineField({
      name: 'availableDocuments',
      title: 'Available Documents (Title & Legal)',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      options: {
        list: [
          {title: 'Certificate of Occupancy (C of O)', value: 'workspace_premium', icon: MdOutlineWorkspacePremium },
          {title: 'Governor`s Consent', value: 'gavel', icon: MdGavel},
          {title: 'Deed of Assignment', value: 'assignment', icon: MdAssignment},
          {title: 'Registered Conveyance', value: 'history_edu', icon: MdArticle},
          {title: 'Survey Plan', value: 'map', icon: MdMap},
          {title: 'Excision / Gazette', value: 'article', icon: MdArticle},
          {title: 'Purchase Receipt', value: 'receipt_long', icon: MdReceiptLong},
          {title: 'Power of Attorney', value: 'supervisor_account', icon: MdSupervisorAccount},
          {title: 'Letter of Allocation', value: 'mark_email_read', icon: MdMarkEmailRead},
          {title: 'Contract of Sale', value: 'handshake', icon: MdHandshake},
          {title: 'Court Judgment', value: 'balance', icon: MdBalance},
          {title: 'Tenancy Agreement', value: 'contract', icon: MdOutlineDocumentScanner },
          {title: 'Building Approval', value: 'building_approval', icon: MdDomainVerification },
        ],
      },
    }),

    // Utilities & Infrastructure
    defineField({
      name: 'utilities',
      title: 'Utilities & Infrastructure',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      options: {
        list: [
          {title: 'Prepaid Meter', value: 'electric_meter', icon: MdElectricalServices},
          {title: 'Postpaid Meter', value: 'receipt', icon: MdReceipt},
          {title: 'Borehole / Treated Water', value: 'water_drop', icon: MdWaterDrop},
          {title: 'Grid Power Supply', value: 'electric_bolt', icon: MdElectricBolt},
          {title: 'Solar Inverter System', value: 'solar_power', icon: MdSolarPower},
          {title: 'Backup Generator', value: 'power', icon: MdPower},
          {title: 'Good Drainage System', value: 'water', icon: MdWaterDrop},
          {title: 'Waste Disposal / Central Bins', value: 'delete', icon: MdDelete},
          {title: 'Septic Tank / Soakaway', value: 'plumbing', icon: MdPlumbing},
          {title: 'Overhead Water Tank', value: 'opacity', icon: MdOpacity},
          {title: 'Water Pumping Machine', value: 'settings_input_component', icon: MdSettingsInputComponent},
          {title: 'Central Air Conditioning', value: 'ac_unit', icon: MdAcUnit},
          {title: 'Central Heating', value: 'thermostat', icon: MdThermostat},
        ],
      },
    }),

    // Community & Lifestyle Amenities
    defineField({
      name: 'communityAmenities',
      title: 'Community & Lifestyle Amenities',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      options: {
        list: [
          {title: 'Parking Space', value: 'directions_car', icon: MdDirectionsCar},
          {title: 'Gated Estate / Community', value: 'fence', icon: MdFence},
          {title: 'Tarred / Paved Roads', value: 'add_road', icon: MdAddRoad},
          {title: 'Street Lights', value: 'light', icon: MdLight},
          {title: 'Supermarket / Grocery', value: 'shopping_cart', icon: MdShoppingCart},
          {title: 'Pharmacy / Clinic', value: 'local_pharmacy', icon: MdLocalPharmacy},
          {title: 'Hospital / Medical Center', value: 'local_hospital', icon: MdLocalHospital},
          {title: 'School / Daycare Nearby', value: 'school', icon: MdSchool},
          {title: 'Church', value: 'church', icon: MdChurch},
          {title: 'Mosque', value: 'mosque', icon: MdMosque},
          {title: 'Children\'s Playground', value: 'child_friendly', icon: MdChildFriendly},
          {title: 'Club House', value: 'deck', icon: MdDeck},
          {title: 'Public Transport / Bus Stop', value: 'directions_bus', icon: MdDirectionsBus},
          {title: 'Bank / ATM Nearby', value: 'local_atm', icon: MdLocalAtm},
          {title: 'Police Station Nearby', value: 'local_police', icon: MdLocalPolice},
          {title: 'Coworking Space', value: 'co_present', icon: MdCoPresent},
        ],
      },
    }),

    // Property Details & Rules
    defineField({
      name: 'propertyRules',
      title: 'Key Property Details & Rules',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      options: {
        list: [
          {title: 'No Generators Allowed', value: 'noise_control_off', icon: MdNoiseControlOff},
          {title: 'No Pets Allowed', value: 'do_not_disturb', icon: MdDoNotDisturb},
          {title: 'Pet Friendly', value: 'pets', icon: MdPets},
          {title: 'Service Charge Applies', value: 'request_quote', icon: MdRequestQuote},
          {title: 'Newly Built', value: 'new_releases', icon: MdNewReleases},
          {title: 'Recently Renovated', value: 'construction', icon: MdConstruction},
          {title: 'Flood Free Zone', value: 'shield', icon: MdShield},
          {title: 'Furnished', value: 'chair', icon: MdChair},
          {title: 'Unfurnished', value: 'check_box_outline_blank', icon: MdCheckBoxOutlineBlank},
          {title: 'Semi-Furnished', value: 'category', icon: MdCategory},
          {title: 'Corner Piece Property', value: 'filter_b_and_w', icon: MdFilterBAndW},
          {title: 'Waterfront Property', value: 'pool', icon: MdWaterDrop},
          {title: 'Owner Occupied', value: 'person', icon: MdChair},
          {title: 'Tenanted', value: 'people', icon: MdPeople},
          {title: 'Commercial Use Allowed', value: 'business', icon: MdBusiness},
          {title: 'Residential Use Only', value: 'home', icon: MdHome},
          {title: 'No Smoking', value: 'smoke_free', icon: MdSmokeFree},
        ],
      },
    }),

    // Luxury & Leisure
    defineField({
      name: 'luxuryAmenities',
      title: 'Luxury & Leisure',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      options: {
        list: [
          {title: 'Swimming Pool', value: 'pool', icon: MdWaterDrop},
          {title: 'Infinity Pool', value: 'waves', icon: MdWaves},
          {title: 'Hot Tub / Jacuzzi', value: 'hot_tub', icon: MdHotTub},
          {title: 'Sauna / Steam Room', value: 'spa', icon: MdSpa},
          {title: 'Wine Cellar', value: 'wine_bar', icon: MdWineBar},
          {title: 'Lounge / Bar Area', value: 'local_bar', icon: MdLocalBar},
          {title: 'Tennis Court / Table Tennis', value: 'sports_tennis', icon: MdSportsTennis},
          {title: 'Basketball Court', value: 'sports_basketball', icon: MdSportsBasketball},
          {title: 'Gym / Fitness Center', value: 'fitness_center', icon: MdFitnessCenter},
          {title: 'Air Hockey', value: 'sports_hockey', icon: MdSportsHockey},
          {title: 'Golf / Mini-Golf', value: 'golf_course', icon: MdGolfCourse},
          {title: 'Snooker', value: 'local_play', icon: MdLocalPlay},
          {title: 'Helipad', value: 'flight_takeoff', icon: MdFlightTakeoff},
          {title: 'Private Boat Dock / Jetty', value: 'directions_boat', icon: MdDirectionsBoat},
          {title: 'Rooftop Lounge', value: 'roofing', icon: MdDeck},
          {title: 'Squash Court', value: 'sports_score', icon: MdSportsScore},
          {title: 'Cigar Lounge', value: 'smoking_rooms', icon: MdSmokingRooms},
          {title: 'Indoor Pool', value: 'water', icon: MdWaterDrop},
          {title: 'NetFlix', value: 'smart_display', icon: MdSmartDisplay},
          {title: 'Dstv (Cable/Satelite)', value: 'connected_tv', icon: MdConnectedTv},
        ],
      },
    }),

    // Advanced Security & Smart Home
    defineField({
      name: 'securityFeatures',
      title: 'Advanced Security & Smart Home',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      options: {
        list: [
          {title: 'Smart Home System', value: 'router', icon: MdRouter},
          {title: 'Video Doorbell', value: 'doorbell', icon: MdDoorbell},
          {title: 'Biometric / Fingerprint Access', value: 'fingerprint', icon: MdFingerprint},
          {title: 'Electric Fence', value: 'bolt', icon: MdElectricBolt},
          {title: 'CCTV Surveillance', value: 'videocam', icon: MdVideocam},
          {title: 'Intercom System', value: 'ring_volume', icon: MdRingVolume},
          {title: 'Motion Sensors', value: 'sensors', icon: MdSensors},
          {title: 'Panic Alarm', value: 'notifications_active', icon: MdNotificationsActive},
          {title: 'Uniformed Security Guard', value: 'local_police', icon: MdLocalPolice},
          {title: 'Armed Patrol', value: 'security', icon: MdSecurity},
          {title: 'Keyless Entry / Smart Lock', value: 'lock', icon: MdLock},
          {title: 'Automated Gates', value: 'garage', icon: MdGarage},
          {title: 'Fire Alarm / Smoke Detector', value: 'detector_smoke', icon: MdSensorWindow},
          {title: 'Security / Bulletproof Doors', value: 'door_front', icon: MdDoorFront},
          {title: 'Burglary Proof / Window Guards', value: 'grid_3x3', icon: MdGrid3X3},
          {title: 'Automated Blinds / Curtains', value: 'blinds', icon: MdBlinds},
        ],
      },
    }),

    // Outdoor & Landscaping
    defineField({
      name: 'outdoorAmenities',
      title: 'Outdoor & Landscaping',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      options: {
        list: [
          {title: 'Rooftop Terrace', value: 'roofing', icon: MdDeck},
          {title: 'Gazebo / Pergola', value: 'holiday_village', icon: MdHolidayVillage},
          {title: 'BBQ / Grilling Area', value: 'outdoor_grill', icon: MdOutdoorGrill},
          {title: 'Outdoor Shower', value: 'shower', icon: MdShower},
          {title: 'Private Garden', value: 'yard', icon: MdYard},
          {title: 'Fountain / Water Feature', value: 'water_drop', icon: MdWaterDrop},
          {title: 'Stamped Concrete Compound', value: 'grid_on', icon: MdGridOn},
          {title: 'Carport / Shaded Parking', value: 'garage', icon: MdGarage},
          {title: 'Fire Pit', value: 'local_fire_department', icon: MdLocalFireDepartment},
          {title: 'Cabana', value: 'beach_access', icon: MdBeachAccess},
          {title: 'Greenhouse / Orchard', value: 'agriculture', icon: MdAgriculture},
          {title: 'Courtyard / Patio', value: 'deck', icon: MdDeck},
          {title: 'Artificial Turf', value: 'grass', icon: MdEco},
        ],
      },
    }),

    // Core Infrastructure
    defineField({
      name: 'coreInfrastructure',
      title: 'Core Utilities & Infrastructure',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      options: {
        list: [
          {title: 'Dedicated Transformer', value: 'electric_bolt', icon: MdElectricBolt},
          {title: 'Water Treatment Plant', value: 'sanitizer', icon: MdSanitizer},
          {title: 'High-Speed Fibre Internet', value: 'wifi_tethering', icon: MdWifiTethering},
          {title: 'Piped Central Gas Line', value: 'gas_meter', icon: MdGasMeter},
          {title: 'Elevator / Lift', value: 'elevator', icon: MdElevator},
          {title: 'Wheelchair Ramp', value: 'accessible_forward', icon: MdAccessibleForward},
          {title: 'Trash Chute', value: 'delete_sweep', icon: MdDeleteSweep},
          {title: 'Central Vacuum System', value: 'cleaning_services', icon: MdCleaningServices},
          {title: 'Backup Battery / UPS Room', value: 'battery_charging_full', icon: MdBatteryChargingFull},
          {title: 'Lightning Arrestor', value: 'flash_on', icon: MdFlashOn},
          {title: 'Fire Sprinkler System', value: 'fire_extinguisher', icon: MdFireExtinguisher},
          {title: 'HVAC System', value: 'hvac', icon: MdAcUnit},
          {title: 'Freight Elevator / Service Lift', value: 'unfold_more', icon: MdElevator},
          {title: 'Dumbwaiter', value: 'kitchen', icon: MdKitchen},
        ],
      },
    }),

    // Specialized Rooms & Spaces
    defineField({
      name: 'specializedRooms',
      title: 'Highly Specific Rooms & Spaces',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      options: {
        list: [
          {title: 'Boys Quarters (BQ) / Maids Room', value: 'cottage', icon: MdHome},
          {title: 'Home Cinema / Theater', value: 'theaters', icon: MdTheaters},
          {title: 'Study Room / Home Office', value: 'desk', icon: MdDeck},
          {title: 'Prayer Room / Mosque / Chapel', value: 'place_of_worship', icon: MdChurch},
          {title: 'Laundry Room', value: 'local_laundry_service', icon: MdCleaningServices},
          {title: 'Mudroom / Foyer', value: 'meeting_room', icon: MdMeetingRoom},
          {title: 'Underground Basement', value: 'foundation', icon: MdHome},
          {title: 'Gaming Room', value: 'sports_esports', icon: MdSportsEsports },
          {title: 'Music / Recording Studio', value: 'mic', icon: MdMic},
          {title: 'Private Library', value: 'menu_book', icon: MdMenuBook},
          {title: 'Sunroom / Conservatory', value: 'wb_sunny', icon: MdWbSunny},
          {title: 'Safe Room / Panic Room', value: 'enhanced_encryption', icon: MdEnhancedEncryption},
          {title: 'Server / IT Room', value: 'dns', icon: MdDns},
          {title: 'Cold Room (Storage)', value: 'ac_unit', icon: MdAcUnit},
          {title: 'Workshop / DIY Room', value: 'handyman', icon: MdHandyman},
          {title: 'Home Salon / Spa', value: 'content_cut', icon: MdContentCut},
        ],
      },
    }),

    // Eco-Friendly & Sustainable
    defineField({
      name: 'ecoFeatures',
      title: 'Eco-Friendly & Sustainable',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      options: {
        list: [
          {title: 'Solar Panels / Inverter', value: 'solar_power', icon: MdSolarPower},
          {title: 'EV Charging Station', value: 'ev_station', icon: MdEvStation},
          {title: 'Natural Light / Floor-to-Ceiling Windows', value: 'light_mode', icon: MdLightMode},
          {title: 'Rainwater Harvesting System', value: 'water_ec', icon: MdWaterDrop},
          {title: 'Energy Efficient Appliances', value: 'eco', icon: MdEco},
          {title: 'Green Roof / Living Wall', value: 'forest', icon: MdForest},
          {title: 'Double Glazed / Insulated Windows', value: 'window', icon: MdWindow},
          {title: 'Composting Area', value: 'recycling', icon: MdRecycling},
          {title: 'Biodigester', value: 'science', icon: MdEco},
          {title: 'Smart Thermostat', value: 'nest_thermostat', icon: MdThermostatAuto},
        ],
      },
    }),

    // Move-in Costs
    defineField({
      name: 'moveInCosts',
      title: 'Move-in Costs',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'item', title: 'Item', type: 'string'}),
            defineField({name: 'detail', title: 'Detail', type: 'string'}),
            defineField({name: 'amount', title: 'Amount', type: 'number'}),
          ],
        }),
      ],
    }),

    defineField({
      name: 'agent',
      title: 'Agent',
      type: 'reference',
      to: [{type: 'agent'}],
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'state',
      media: 'gallery.0',
    },
  },
})
